// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ShortMaker - Transforme seus vídeos em Shorts Virais",
  description: "IA avançada que identifica os melhores momentos do seu vídeo e cria shorts automaticamente. Simples, rápido e profissional.",
  keywords: ["shorts", "vídeo", "IA", "viral", "youtube", "tiktok", "instagram"],
  authors: [{ name: "ShortMaker" }],
  openGraph: {
    title: "ShortMaker - Transforme seus vídeos em Shorts Virais",
    description: "IA avançada que identifica os melhores momentos do seu vídeo e cria shorts automaticamente.",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "ShortMaker - Transforme seus vídeos em Shorts Virais",
    description: "IA avançada que identifica os melhores momentos do seu vídeo e cria shorts automaticamente.",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}